export {   AddOutlined,
   ArrowDownOutlined,
   ArrowUpOutlined,
   ArrowLeftOutlined,
   ArrowRightOutlined,
   ArrowGrowthOutlined,
   ArrowDeclineOutlined,
   CalendarOutlined,
   ChevrownDownOutlined,
   ChevrownLeftOutlined,
   ChevrownRightOutlined,
   ChevrownUpOutlined,
   CheckCircleOutlined,
   CheckOutlined,
   CornerRightDownOutlined,
   CrossCircleOutlined,
   CrossOutlined,
   DeleteOutlined,
   DocumentOutlined,
   DownloadOutlined,
   EditOutlined,
   ErrorOutlined,
   ExternalLinkOutlined,
   HideOutlined,
   ImageOutlined,
   LinkOutlined,
   LoaderOutlined,
   LocationOutlined,
   LogoutOutlined,
   LongArrowDownOutlined,
   LongArrowLeftOutlined,
   LongArrowRightOutlined,
   LongArrowUpOutlined,
   MoreVerticalOutlined,
   PauseCircleOutlined,
   ProcessingOutlined,
   RetryOutlined,
   SendOutlined,
   SearchOutlined,
   ShowOutlined,
   TopOutlined,
   UploadHoverOutlined,
   UploadOutlined,
   UploadingOutlined,
   WaitingOutlined,
   UploadPausedOutlined,
   UserCircleOutlined,
   UserProfileOutlined,
   UserUnverifyOutlined,
   WifiOffOutlined,
   WifiOutlined,
   DocumentSearcchOutlined,} from './outlined';


   export { AlertOutlined, AlertTriangleOutlined, CodeSnippetOutlined, CopyOutlined,
      FilterOutlined,
      HelpOutlined,
      InfoOutlined,
      MaximizeOutlined,
      MinimizeOutlined,
      MuteOutlined,
      ReviewOutlined,
      SettingsOutlined,
      SoundOnOutlined,
      TextBoldOutlined,
      TextItalicOutlined,
      ThumbDownOutlined,
      ThumbUpOutlined,} from './outlined2';

      export {
         InfoFilled,
         CheckFilled,
         DropDownFilled,
         DropDownUpFilled,
         ErrorFilled,
         FilterClearFilled,
         FilterStrokeFilled,
         GridFilled,
         UnverifiedFilled,
         ListFilled,
         PauseFilled,
         PlayFilled,
         TriangleDownFilled,
         TriangleUpFilled,
       } from './filled';
       export {
         UsersTwoTone,
         DocumentTwoTone,
         ImageTwoTone,
         KeyTwoTone,
         LinkTwoTone,
         LiveTVTwoTone,
         MetaDataTwoTone,
         MovieTwoTone,
         PlatformsTwoTone,
         PlayTwoTone,
         SeriesTwoTone,
         Series1TwoTone,
         Series2TwoTone,
         SingleVideoTwoTone,
         SongTwoTone,
         TimeCircleTwoTone,
         VideoTwoTone,
         ViewsTwoTone,
         CalendarTwoTone,
       } from './two-tone';